/* Editorial content is separate from presentation. Values marked pending must be confirmed by ACN. */
const COPY = {
  pt: {
    skip:'Saltar para o conteúdo', navLabel:'Navegação principal', menuLabel:'Abrir menu', closeMenu:'Fechar menu', navSystems:'Sistemas', navServices:'Serviços', navContact:'Contactos', quote:'Pedir proposta',
    title:'ACN Cutting Systems — Engenharia à medida da sua produção', meta:'Sistemas de corte laser de fibra, plasma, oxicorte e furação. Engenharia e fabrico ACN Cutting Systems, em Portugal.',
    heroEyebrow:'ACN Cutting Systems · Grupo Motofil', heroTitle1:'Engenharia que', heroTitle2:'define o corte.', heroIntro:'Laser de fibra, plasma, oxicorte e furação. Sistemas de corte desenvolvidos e fabricados de raiz em Ílhavo, Portugal.', explore:'Explorar sistemas', scroll:'Deslize para descobrir',
    whatEyebrow:'01 / O que fazemos', whatTitle:'A máquina certa começa na sua peça.', whatBody:'A ACN concebe, desenvolve e fabrica sistemas industriais de corte para o processamento de metal. Estrutura, movimento, controlo e software são desenvolvidos internamente, para configurar a máquina às peças que realmente produz.', whatGroup:'Parte do Grupo Motofil, que desenvolve soluções industriais desde 1981, em mais de 30 países.', metricACN:'Anos a fabricar máquinas de corte', metricGroup:'Anos de engenharia do grupo', metricCountries:'Países servidos', metricInhouse:'Fabrico interno',
    rangeEyebrow:'02 / Os nossos sistemas', rangeTitle:'um fornecedor. múltiplas soluções.', rangeBody:'Sistemas de corte à medida da sua produção. Laser de fibra, plasma, oxicorte e furação para processamento de chapa e tubo — individuais ou combinados. Desenvolvidos para as suas necessidades.', filterLabel:'Filtrar máquinas', filterAll:'Todos os sistemas', filterSheet:'Laser · Chapa', filterTube:'Laser · Tubo', filterPlate:'Plasma & Oxicorte', systems:'sistemas', fullSpecs:'Especificações completas disponíveis mediante pedido.', askCatalogue:'Pedir catálogo',
    photoPending:'Fotografia por adicionar', pending:'Por confirmar', blank:'', sheetTag:'Laser de fibra · Chapa', tubeTag:'Laser de fibra · Tubo', plasmaTag:'Plasma', oxyTag:'Plasma / Oxicorte', multiTag:'Multiprocesso', dynamicTag:'Mesa dinâmica', models:'Modelos', specifications:'Especificações', addons:'Add-ons', custom:'Personalizado', standard:'Standard', configure:'Falar sobre esta máquina', engineering:'Departamento de engenharia disponível para desenvolver outras soluções mediante pedido.',
    workingArea:'Área de trabalho', customArea:'Área de trabalho personalizada', source:'Potência da fonte', minSheet:'Chapa mínima', maxSheet:'Chapa máxima', maxWeight:'Peso máximo', minDiameter:'Diâmetro mínimo', maxDiameter:'Diâmetro máximo', loadingLength:'Comprimento de carga', cutThickness:'Espessura de corte', current:'Corrente de plasma', tableLength:'Comprimento da mesa', tableWidth:'Largura da mesa', oxy:'Oxicorte', bevelAngle:'Ângulo de bisel', drill:'Furação Ø', stations:'Estações de ferramentas', cutArea:'Área máx. de corte', maxPlate:'Peso máx. da chapa', positioning:'Posicionamento', minWorkingArea:'Área de trabalho mínima', cuttingAngle:'Ângulo de corte',
    facilityAlt:'Instalações de fabrico ACN em Ílhavo', facilityCaption:'Chão de fábrica · Ílhavo, Portugal', servicesEyebrow:'acn cutting systems made in portugal', servicesTitle:'Da estrutura ao primeiro corte. Sob o mesmo teto.', servicesBody:'O metal é soldado, maquinado e montado nas nossas instalações. Os quadros elétricos são cablados internamente e cada máquina é testada e validada antes da expedição.', serviceTitle:'Assistência & formação', serviceBody:'A nossa equipa SAT presta apoio técnico, formação de operadores e diagnóstico remoto, ajudando a manter a sua máquina no melhor desempenho ao longo de toda a sua vida útil.', consumablesTitle:'Consumíveis', consumablesBody:'Os clientes têm acesso a stock permanente e a consumíveis fiáveis para apoiar os seus sistemas de corte ACN ao longo de toda a sua vida útil.',
    contactEyebrow:'04 / Vamos falar', contactTitle:'O seu próximo corte começa aqui.', contactBody:'Diga-nos o material, a espessura e o formato com que trabalha. Encontraremos os sistemas adequados à sua produção — e uma proposta.', phone:'Telefone', address:'Morada', requiredNote:'* Campos obrigatórios', nameLabel:'Nome *', companyLabel:'Empresa', mobileLabel:'Telemóvel (opcional)', messageLabel:'Mensagem *', messagePlaceholder:'Material, espessura, formato, volume…', formNote:'Os seus dados serão utilizados para responder ao seu pedido.', send:'Enviar pedido', sending:'A enviar…', success:'Pedido enviado. A equipa ACN entrará em contacto consigo.', unavailable:'Não foi possível enviar o pedido. Os seus dados foram mantidos. Tente novamente ou contacte geral@acncutting.com.', invalid:'Verifique os campos e tente novamente.', rateLimited:'Foram efetuadas várias tentativas. Aguarde alguns minutos ou contacte geral@acncutting.com.', interest:'Tenho interesse no sistema', footerLine:'Engenharia portuguesa. Precisão sem fronteiras.', backTop:'Voltar ao topo', group:'Uma empresa do Grupo Motofil'
  },
  en: {
    skip:'Skip to content', navLabel:'Main navigation', menuLabel:'Open menu', closeMenu:'Close menu', navSystems:'Systems', navServices:'Services', navContact:'Contacts', quote:'Request a quote',
    title:'ACN Cutting Systems — Engineered around your production', meta:'Fibre laser, plasma, oxy-fuel and drilling systems. Engineered and manufactured by ACN Cutting Systems in Portugal.',
    heroEyebrow:'ACN Cutting Systems · Motofil Group', heroTitle1:'Machines that', heroTitle2:'cut to the line.', heroIntro:'Fibre laser, plasma, oxy-fuel and drill cutting systems, engineered and built end to end in Ílhavo, Portugal.', explore:'Explore systems', scroll:'Scroll to discover',
    whatEyebrow:'01 / What we do', whatTitle:'We build the machine around the part.', whatBody:'ACN designs, engineers and manufactures industrial cutting systems for metal processing. Structure, motion, control and software are developed in-house, which means a machine can be configured to the parts you actually cut instead of the other way round.', whatGroup:'Part of the Motofil Group, automating factories since 1981 across more than 30 countries.', metricACN:'Years manufacturing cutting machines', metricGroup:'Years of group engineering', metricCountries:'Countries served', metricInhouse:'Built in-house',
    rangeEyebrow:'02 / The range', rangeTitle:'one supplier. multiple solutions.', rangeBody:'Cutting systems, built around your production. Fibre laser, plasma, oxy-fuel and drilling for sheet metal and tube processing — individual or combined. Engineered to your needs.', filterLabel:'Filter machines', filterAll:'All systems', filterSheet:'Fibre laser · Sheet', filterTube:'Fibre laser · Tube', filterPlate:'Plasma & Oxy-fuel', systems:'systems', fullSpecs:'Full specifications available on request.', askCatalogue:'Ask for the catalogue',
    photoPending:'Photo pending', pending:'To confirm', blank:'', sheetTag:'Fibre laser · Sheet metal', tubeTag:'Fibre laser · Tube', plasmaTag:'Plasma', oxyTag:'Plasma / Oxy-fuel', multiTag:'Multiprocess', dynamicTag:'Dynamic table', models:'Models', specifications:'Specifications', addons:'Add-ons', custom:'Custom', standard:'Standard', configure:'Discuss this machine', engineering:'Engineering department available to develop other solutions as requested.',
    workingArea:'Working area', customArea:'Custom-made working area', source:'Source power', minSheet:'Min. sheet', maxSheet:'Max. sheet', maxWeight:'Max. weight', minDiameter:'Min. diameter', maxDiameter:'Max. diameter', loadingLength:'Loading length', cutThickness:'Cut thickness', current:'Plasma current', tableLength:'Table length', tableWidth:'Table width', oxy:'Oxy-fuel', bevelAngle:'Bevel angle', drill:'Drill Ø', stations:'Tool stations', cutArea:'Max. cut area', maxPlate:'Max. plate', positioning:'Positioning', minWorkingArea:'Min. working area', cuttingAngle:'Cutting angle',
    facilityAlt:'ACN manufacturing facility, Ílhavo', facilityCaption:'Assembly floor · Ílhavo, Portugal', servicesEyebrow:'acn cutting systems made in portugal', servicesTitle:'One roof, from steel frame to first cut.', servicesBody:'Metal is welded, machined and assembled in our own facilities. Control cabinets are wired in-house, and every machine is run and validated before it ships.', serviceTitle:'Service & training', serviceBody:'Our SAT team provides technical support, operator training and remote diagnostics, helping you keep your machine running at its best throughout its working life.', consumablesTitle:'Consumables', consumablesBody:'Customers have access to permanent stock and reliable consumables to support their ACN cutting systems throughout their working life.',
    contactEyebrow:'04 / Get in touch', contactTitle:'Tell us what you cut.', contactBody:'Send the material, thickness and format you work with and we will come back with the systems that fit — and a quote.', phone:'Phone', address:'Address', requiredNote:'* Required fields', nameLabel:'Name *', companyLabel:'Company', mobileLabel:'Mobile phone (optional)', messageLabel:'Message *', messagePlaceholder:'Material, thickness, format, volume…', formNote:'Your details will be used to respond to your enquiry.', send:'Send request', sending:'Sending…', success:'Request sent. The ACN team will get in touch with you.', unavailable:'Your request could not be sent. Your details have been kept. Please try again or contact geral@acncutting.com.', invalid:'Please check your details and try again.', rateLimited:'Too many attempts. Please wait a few minutes or contact geral@acncutting.com.', interest:'I am interested in the', footerLine:'Portuguese engineering. Precision without borders.', backTop:'Back to top', group:'A Motofil Group company'
  }
};
const L = (pt, en) => ({pt, en});
const MACHINES = [
  {id:'smartline', cat:'sheet', tag:'sheetTag', name:'SMARTLINE', image:'img/catalogue/SmartLine.webp',
    description:L('Laser de fibra 2D compacto para processamento de chapa. Dois modelos, a mesma fonte, ajustados ao seu formato de produção.','Compact 2D fibre laser for sheet metal processing. Two models, the same source, configured around your production format.'),
    models:[{id:'1530', name:'1530', area:'3000 × 1500 mm'}, {id:'2040', name:'2040', area:'4000 × 2000 mm'}],
    specs:[['workingArea','3000 × 1500 — 4000 × 2000 mm'],['source',null]],
    addons:[]},
  {id:'mfl', cat:'sheet', tag:'sheetTag', name:'MFL', image:'img/catalogue/MFL.webp',
    description:L('Laser de fibra industrial para chapa, com troca automática de mesas e área de trabalho configurável à medida da sua produção.','Industrial fibre laser for sheet metal, with automatic table exchange and a working area configured around your production.'),
    specs:[['workingArea','3000 × 1500 — 8000 × 2500 mm'],['customArea',L('A partir de 12000 × 4000 mm · personalizado','From 12000 × 4000 mm · custom')],['source','4–30 kW'],['minSheet','3000 × 1500 mm'],['maxSheet','4000 × 2000 mm'],['maxWeight',null]],
    addons:[
      {title:L('Carregador e descarregador automático de chapa','Automatic sheet loader and unloader'), text:L('Formato máximo de chapa: 4000 × 2000 mm.','Maximum sheet format: 4000 × 2000 mm.')},
      {title:L('Bizelador','Bevel head'), text:L('Área de trabalho mínima: 6000 × 2500 mm. Disponível apenas neste formato ou superior. Ângulo de corte: +45º/−45º.','Min. working area: 6000 × 2500 mm. Available only for this size or larger. Cutting angle: +45º/−45º.')},
      {title:L('Troca automática de bicos','Automatic nozzle change'), text:L('28 bicos','28 nozzles'), pending:true},
      {title:L('Limpeza automática','Automatic cleaning')}, {title:L('Calibração automática','Automatic calibration')},
      {title:L('Melhorias personalizadas mediante pedido','Custom improvement as requested')}
    ]},
  {id:'sheet-metal', cat:'sheet', tag:'sheetTag', name:'Sheet Metal', image:'img/catalogue/SheetMetal.webp',
    description:L('Sistema para processamento de chapa, com configuração técnica a confirmar.','Sheet metal processing system, with technical configuration to be confirmed.'),
    specs:[['workingArea',null],['source',null],['maxWeight',null]], addons:[]},
  {id:'tube-smart', cat:'tube', tag:'tubeTag', name:'Laser Tubo Smart', nameEn:'Laser Tube Smart', image:'img/catalogue/LaserTubeSmart.webp',
    description:L('Corte de tubos e perfis com opções de carregamento para diferentes necessidades de produção.','Tube and profile cutting with loading options for different production requirements.'),
    specs:[['minDiameter','Ø 120 mm'],['maxDiameter','Ø 220 mm'],['maxWeight',''],['loadingLength',L('6000 mm · personalizado','6000 mm · custom')]],
    addons:[{title:L('Carregador standard de 5 tubos','Standard 5-tube loader'), text:L('Comprimento do tubo: 6000 mm.','Tube length: 6000 mm.')}, {title:L('Carregador automático','Automatic loader'),text:L('Comprimento do tubo: 6000 mm.','Tube length: 6000 mm.')}, {title:L('Personalizado','Custom'),engineering:true}]},
  {id:'tube-heavy', cat:'tube', tag:'tubeTag', name:'Laser Tubo Heavy', nameEn:'Laser Tube Heavy', image:'img/catalogue/LaserTubeHeavy.webp',
    description:L('Sistema para corte de tubos e perfis de grande dimensão, com soluções personalizadas de carga e processamento.','Heavy tube and profile cutting with customised loading and processing solutions.'),
    variants:[{id:'standard',label:'standard', specs:[['minDiameter','Ø 320 mm'],['maxDiameter','Ø 690 mm'],['loadingLength','12000 mm']]},{id:'custom',label:'custom',specs:[['minDiameter','Ø 690 mm'],['maxDiameter',L('Personalizado','Custom')]]}],
    specs:[['minDiameter','Ø 320 mm'],['maxDiameter','Ø 690 mm'],['loadingLength','12000 mm']],
    addons:[{title:L('Bizelador','Bevel head'),text:L('Ângulo de corte: +45º/−45º.','Cutting angle: +45º/−45º.')}, {title:L('Componentes de máquina personalizados','Customized machine parts')}, {title:L('Peso máximo','Max. weight'),pending:true}]},
  /* Plasma values and existing English descriptions preserved from the original landing page. */
  {id:'feline',cat:'plate',tag:'plasmaTag',name:'Feline',image:'img/catalogue/Feline.webp',description:L('Célula de plasma compacta de alta precisão — mesa e pórtico integrados numa única estrutura.','Compact high-precision plasma cell — table and gantry integrated in one structure.'),specs:[['workingArea','≤ 6000 × 2000 mm'],['cutThickness','≤ 25 mm'],['current',L('Até 200 A','Up to 200 A')]],addons:[]},
  {id:'dragom',cat:'plate',tag:'oxyTag',name:'DRAGOm',image:'img/catalogue/DragoM.webp',description:L('Pórtico robusto para chapa com plasma e oxicorte, que acompanha a sua produção.','Robust plate gantry for plasma and oxy-fuel, scaling with your production.'),specs:[['tableLength','6 – 30 m'],['tableWidth','2.5 – 4.5 m'],['oxy','≤ 200 mm']],addons:[]},
  {id:'dragomx',cat:'plate',tag:'multiTag',name:'DRAGOm Multiprocess',image:'img/catalogue/DragoM_Multiprocessos.webp',description:L('Cabeças de bisel, furação e marcação num único pórtico — sem mudança de configuração entre processos.','Bevel, drilling and marking heads on one gantry — no setup change between processes.'),specs:[['bevelAngle','± 60°'],['drill','≤ 40 mm'],['stations','5']],addons:[]},
  {id:'taurus',cat:'plate',tag:'dynamicTag',name:'Taurus',image:'img/catalogue/Taurus.webp',description:L('Mesa dinâmica para corte térmico, furação e roscagem de grande volume — a chapa move-se, não o pórtico.','Dynamic table for high-volume thermal cutting, drilling and tapping — the plate moves, not the gantry.'),specs:[['cutArea','12 000 × 3 000 mm'],['maxPlate','14 000 kg'],['positioning','± 0.3 mm']],addons:[]}
];
/* Future hero media: set video to a local MP4/WebM, or add a third image to frames.
   Existing photograph paths remain unchanged until final assets are provided. */
const HERO_MEDIA = {video:null, frames:['img/smartline-1530.png','img/head-detail.jpg']};
